### ISSUE TITLE
BUG: Check the package spelling or your minimum-stability

### ISSUE THREAD

**Issue by sanchezcarlosjr** [exonos/mailapi#1]
[InvalidArgumentException] Could not find package  at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

https://stackoverflow.com/questions/41149552/composer-packagist-could-not-find-package-for-minimum-stability

**Comment by exonos** [comment]
Hi @sanchezcarlosjr,

Thank you for your contribution and for pointing out this issue.

The problem you encountered was indeed due to the absence of an official release. We have now created the first official release to address this.

Please try again and let us know if you encounter any further issues. We apologize for any inconvenience this may have caused and appreciate your patience.

Thanks again for your contribution!
